# Generated by Django 5.1.7 on 2025-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'script',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='passowrd',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
