# Generated by Django 5.1.7 on 2025-04-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_script_rename_passowrd_signup_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'managed': False},
        ),
    ]
